### ISSUE TITLE
Juan Rodriguez: PR - Good job! 

### ISSUE THREAD

**Issue by suabochica** [laubeltran01/dart-projects#48]
https://github.com/laubeltran01/dart-projects/blob/f02b10d691ba010a150361d1949950948529083f/Homework/movie_api/lib/channel.dart#L1

Good job Juan! good understanding of the project structure and the responsibilities of the application channel, controller, model and migrations.

It were pending the `getItemById`, `getAll`, `postItem` and `deleteItem` actions. Also the unit tests are missing.

**Comment by Juan7655** [comment]
I respectfully have to disagree. The MovieController class extends ManagedObjectController, which actually implements the endpoints you are mentioning. That is, all endpoints were implemented, I made sure of it

**Comment by suabochica** [comment]
Gotcha! I can see that you are using [ManagedObjectController](https://pub.dev/documentation/aqueduct/latest/aqueduct/ManagedObjectController-class.html) resource offer by Aqueduct. Next time you can clarify this functionality with a comment.
